version: "3.9"
services:
    alpine:
        env_file:
            - .env
        build:
            context: .
            dockerfile: dockerfile.alpine
        volumes:
            - ./scripts:/scripts
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        command: tail -f /dev/null

    ubuntu:
        env_file:
            - .env
        build:
            context: .
            dockerfile: dockerfile.ubuntu
        volumes:
            - ./scripts:/scripts
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        command: tail -f /dev/null
