version: "3.9"
services:
    alpine:
        env_file:
            - .env
        build:
            context: .
            dockerfile: dockerfile.alpine
            args:
                FISH: ${FISH}
                FZF: ${FZF}
                FDFIND: ${FDFIND}
                NVIM: ${NVIM}
                NODE: ${NODE}
                NODE_VERSION: ${NODE_VERSION}
                OHMYFISH: ${OHMYFISH}
                OHMYBASH: ${OHMYBASH}
                UNATTENDED: ${UNATTENDED}
        volumes:
            - ./scripts:/scripts
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

    ubuntu:
        env_file:
            - .env
        build:
            context: .
            dockerfile: dockerfile.ubuntu
            args:
                FISH: ${FISH}
                FZF: ${FZF}
                FDFIND: ${FDFIND}
                NVIM: ${NVIM}
                NODE: ${NODE}
                NODE_VERSION: ${NODE_VERSION}
                OHMYFISH: ${OHMYFISH}
                OHMYBASH: ${OHMYBASH}
                UNATTENDED: ${UNATTENDED}
        volumes:
            - ./scripts:/scripts
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
